baseURL                    = "https://orianna-zzo.github.io/"
builddrafts                = false
languageCode               = "zh-Hans"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 5

theme                      = "AllinOne"
title                      = "ZHENG Zi'ou"

pygmentsuseclasses         = true


[permalinks]
  sci-tech                 = "sci-tech/:year-:month/:slug/"
  project                  = "project/:slug/"
  blog                     = "blog/:year-:month/:slug/"
  profile                  = "profile/:slug/"
  

[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Sci-Tech"
    weight                 = 1
    identifier             = "sci-tech"
    url                    = "/sci-tech/"

  # [[menu.main]]
  #   name                   = "Project"
  #   weight                 = 2
  #   identifier             = "project"
  #   url                    = "/project/"

  [[menu.main]]
    name                   = "Blog"
    weight                 = 3
    identifier             = "blog"
    url                    = "/blog/"

  # [[menu.main]]
  #   name                   = "Profile"
  #   weight                 = 5
  #   identifier             = "profile"
  #   url                    = "/profile/"


[params]
  faviconfile              = "img/zheng.png"
  avatar                   = "img/profile.png"             # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
  author                   = "ZHENG Zi'ou"
  description              = ["Be myself.", "Love the wonderful world.", "Do the right things and be a better man."]           # appears in the site header when set to a non-empty string
  welcome_head             = "Hello, World!"
  welcome_word             = "~ No Day But Today ~"

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false       

  # slides
  slidesDirPath            = "/static/img/header-slides"    # path to image in local dir (for hugo)
  slidesDirPathURL         = "/img/header-slides"    # path to image in static dir (for static pages)

  

  # highlighting 
  highlightjs              = true
  

  # links
  email                    = "zhengziou@gmail.com"
  github                   = "//github.com/orianna-zzo"
  linkedin                 = "//linkedin.com/in/ziouzheng"
  # facebook                 = "//facebook.com/profile.php?id=100001597502469"
  # googleplus               = "//plus.google.com/u/0/114708482192918964838"
  # twitter                  = "//twitter.com/ZhengZiou"
  # px500                    = "//px500"
  instagram                = "//instagram.com/seagulldreamer/"
  include_rss              = false                         # include RSS <link> tag in <head> and show RSS icon


  # analytics
  googleAnalytics          = "UA-90057853-1"
